spring:
  datasource:
    druid:
      enable: true
      db-type: mysql
      username: root
      password: wowangle
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      url: jdbc:p6spy:mysql://123.58.210.7:3306/security?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      initial-size: 10
      min-idle: 10
      max-active: 40
      max-wait: 60000
      test-while-idle: false
      pool-prepared-statements: false #mysql建议关闭 oracle开启
      filters: stat,wall
      filter:
        wall:
          enabled: true
          config:
            commentAllow: true
            multiStatementAllow: true
            noneBaseStatementAllow: true
  redis:
    host: 123.58.210.7
    port: 6379
    password: wowangle;
    database: 10
